### ISSUE TITLE
Converter - convert thankyou/like into default MyBB reputation system

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_Thank-you-like-plugin#105]
Converter - convert thankyou/like thx/likes into MyBB stock reputation system.

It would be nice to add this option to our converter for users whose wanna return tu stock MyBB reputation system.

This feature will be propably needed if you wanna keep all data during migration to MyBB 2.0 in future

What do you think guys? @WhiteNeo @SvePu

**Comment by Cu8eR** [comment]
@SvePu @WhiteNeo 

Can you look into is please? Here is my idea. Feel free to customize it. Thank you!

`INSERT INTO mybb_reputation (uid, adduid, pid, reputation, dateline, comments) SELECT puid AS uid, uid, pid, 1, dateline, 'Imported from Thankyou/Like' FROM mybb_thankyoulike; `

**Comment by Eldenroot** [comment]
I am closing this one... for anybody interested the code above should be working fine.
