### ISSUE TITLE
Show post with most received thanks/likes in the member profile page

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_Thank-you-like-plugin#149]
Show post with most received thanks/likes in the member profile page

**Comment by Eldenroot** [comment]
@SvePu - is there any way to add it?

**Comment by SvePu** [comment]
I'll take a look ... ;)

**Comment by Eldenroot** [comment]
Great, please let me know. Do you know what I mean with this feature request? Do you have Discord, please feel free to text me (@Eldenroot at MyBB channel).

**Comment by Eldenroot** [comment]
No, I meant contact me via Discord channel if you are online to discuss this feature together :)


About this issue:
I would like to add a "box" in member profile where will be displayed the post (link) to the post and the name of the thread and display how many thanks/likes received. So every user will have its the most popular post displayed on memberprofile page.

**Comment by Eldenroot** [comment]
MAybe something like this (MyReactions plugin) - the bottom part - https://user-images.githubusercontent.com/778890/34320411-1dd446ce-e7fa-11e7-8879-584642923de5.png

**Comment by SvePu** [comment]
OK...you mean a box with only one linked post / thread and the number of thanks/likes of that post

**Comment by Eldenroot** [comment]
Yes, exactly. The most liked/thanked post from the user.

**Comment by Eldenroot** [comment]
@SvePu - how is this going, is that possible?

**Comment by SvePu** [comment]
@Eldenroot - I'm working on it ;)

**Comment by SvePu** [comment]
@Eldenroot 
Please check for issues...for me it works

![tyl_plugin_ 149](https://user-images.githubusercontent.com/9826631/41748185-0d595010-75b1-11e8-8bd9-79b8c7ae4237.JPG)

**Comment by Eldenroot** [comment]
Great, few ideas:
- make number of thanks/likes clickable - show who added thx/like
- add forum or category where the thread is located

What about the limit of characters in ppst content, is it configurable via ACP? Does it strip all mycodes, text formatting or how does it work? 

Anyway it is really nice, good job my friend, you are awesome. I will test it on Sunday, not at home until that.

**Comment by Eldenroot** [comment]
One more idea - is possible to show thread prefix for thread where the post is posted?

**Comment by SvePu** [comment]
@Eldenroot
> make number of thanks/likes clickable - show who added thx/like

I guess thats to much .. user can click on post link and see the tyl list under the post in thread

The other points I'll check

**Comment by SvePu** [comment]
Added more plugin settings and thread/forum links on member profile page

![tyl_plugin_ 149_settings](https://user-images.githubusercontent.com/9826631/41781402-b03fac26-7637-11e8-84b9-aa798aecda70.JPG)

![tyl_plugin_ 149_profile_view](https://user-images.githubusercontent.com/9826631/41781411-b563bf62-7637-11e8-801d-d40347e279c2.JPG)

**Comment by Eldenroot** [comment]
You are right, looks really good. Do you plan to add anything more?

**Comment by Eldenroot** [comment]
I really like "read more" button :) I will test it tommorow. Thank you for your hard work

**Comment by SvePu** [comment]
I removed the "read more" button because there is a post link now

I added 2 more templates to display content or nothing to show
![tyl_plugin_ 149_profile_view_nocontent](https://user-images.githubusercontent.com/9826631/41812200-0a842756-771f-11e8-83e7-7c99f02382ff.JPG)

**Comment by Eldenroot** [comment]
@SvePu - works fine, just tested :) cool feature, thank you!

I will release a new version, is there anything what do you wanna to add into this version? Thank you!
