### ISSUE TITLE
Add new setting - add reputation points

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_Thank-you-like-plugin#155]
https://community.mybb.com/thread-169382-post-1305384.html#pid1305384

@SvePu - can I ask you to add this as a new setting? Thank you very much!

**Comment by SvePu** [comment]
@Eldenroot  - Please test the settings and functions changings ;)

**Comment by Eldenroot** [comment]
@SvePu - great, thank you!
