### ISSUE TITLE
Possible to migrate to this plugin ?

### ISSUE THREAD

**Issue by WallBB** [Eldenroot/MyBB_Thank-you-like-plugin#156]
Hi Eldenroot,
Is it possible to migrate to this plugin from Whiteneo version ?
I am currently using below plugin and would like to shift to this one
https://community.mybb.com/mods.php?action=view&pid=67
Regards
WallBB

**Comment by WallBB** [comment]
@SvePu I haven't tried it, I thought I will ask before doing conversion :)

**Comment by SvePu** [comment]
I also didn't tried it ... please make a db backup before converting!

**Comment by WallBB** [comment]
Closing this issue, I am sticking with the older plugin for now.
