### ISSUE TITLE
"Recount Thank You/Like" in ACP does not take excluded forums into account

### ISSUE THREAD

**Issue by lairdshaw** [Eldenroot/MyBB_Thank-you-like-plugin#157]
This seems to be because the function acp_tyl_do_recounting() in inc/plugins/thankyoulike.php does not even check the value of the 'g33k_thankyoulike_exclude' setting.

I can submit a PR which I *think* fixes this, but am not very familiar with this code so would need you guys to check that it's doing the right thing.

**Comment by Eldenroot** [comment]
Thank you for bug report, feel free to submit a PR, thx

**Comment by SvePu** [comment]
Thanks @lairdshaw for fixing issue

**Comment by lairdshaw** [comment]
You're welcome, @SvePu. As a follow-up, I wonder whether it should be documented somewhere that if you exclude a forum that already has liked posts in it, you need to rebuild the tyl counters?

**Comment by SvePu** [comment]
You're right @lairdshaw ... Maybe we should let run the recounting automatically after changing the exclude forums settings.

**Comment by Eldenroot** [comment]
That would be great, could save a lot of issues
