### ISSUE TITLE
Automatically recount after saving excluded forums

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_Thank-you-like-plugin#159]

**Comment by Eldenroot** [comment]
I was thinking about this and it would not be server friendly - especially for a big boards where this task could take a lot of memory and computing power. I will add a note into ACP about this, what do you think others?

**Comment by lairdshaw** [comment]
Agreed. The plugin should probably take its cue from MyBB core - i.e. in the ACP under Forum Management if you edit a forum and toggle one of the "Yes, [posts/threads] in this forum should count towards user [post/thread] counts" checkboxes and then save, the recount is not automatic; you have to do it manually through Recount & Rebuild. It would be nice though to as you suggest have a note in the ACP about this.

**Comment by Eldenroot** [comment]
I will add a note in my next commit (probably after we merge your PR).

**Comment by Eldenroot** [comment]
@lairdshaw - done, please check if it is enough :)

**Comment by SvePu** [comment]
@Eldenroot - you could replace in both lines:
```
Recount & Rebuild in ACP
```
with
```
<a href=\"index.php?module=tools-recount_rebuild\">Recount & Rebuild in ACP</a>
```

**Comment by lairdshaw** [comment]
Good idea, @SvePu.

**Comment by Eldenroot** [comment]
Ok, I will. @lairdshaw are youon Discord or on mybb board, nickname please.

**Comment by lairdshaw** [comment]
@Eldenroot I'm [Laird](https://community.mybb.com/user-116662.html) on the MyBB Community Forums.
